### ISSUE TITLE
AS25PHP2HRA проблемы с обновлением статуса

### ISSUE THREAD

**Issue by positiveviking** [and7ey/haier_evo#10]
Сетап: 3 одинаковых кондиционера AS25PHP2HRA, включался и управлялся только один.
Подложен файл AS20HPL2HRA.yaml -> AS25PHP2HRA.yaml, номера параметров в сообщении статуса соответствуют

[home-assistant_haier_evo.log](https://github.com/user-attachments/files/15892648/home-assistant_haier_evo.log)

Особенности:
-  необработанный `"event": "deviceStatusEvent"` 
- `Got a message for a different device. Expected: <mac other>, got: <controlled mac>`
- Нет ни одного `"event":"command_response"`

**Comment by positiveviking** [comment]
UPD
Обнаружил что в отправляемых командах остались `"commandName": "3"`  (не соответствует настройке из yaml).
Добавил интеграцию заново и  заработал статус и управление.

Осталась только проблема с несоответствием устройств (aka `Got a message for a different device`),

**Comment by and7ey** [comment]
@positiveviking с вашим PR все работает корректно? ;)
можно закрывать issue?

**Comment by positiveviking** [comment]
В итоге возникла проблема с подключением похожая на какое-то лимитирование аккаунта. От плагина пришлось отказаться и вернуться на интеграцию через УДЯ с пробросом в HA.

**Comment by and7ey** [comment]
> В итоге возникла проблема с подключением похожая на какое-то лимитирование аккаунта. От плагина пришлось отказаться и вернуться на интеграцию через УДЯ с пробросом в HA.

Как выглядело лимитирование аккаунта? у меня такое было, когда я множество попыток входа делал.  Сутки потом залогиниться нельзя было.
