### ISSUE TITLE
Добавил HSU-09HPL203/R3(IN)

### ISSUE THREAD

**Issue by alexxx113** [and7ey/haier_evo#14]
Конфиг HSU-09HPL20.yaml

`
command_name: "4"
attributes:
  - name: current_temperature
    id: "36"
  - name: mode
    id: "2"
    mappings:
      - haier: 0
        value: auto
      - haier: 1
        value: cool
      - haier: 2
        value: dry
      - haier: 4
        value: heat
      - haier: 6
        value: fan_only
  - name: fan_mode
    id: "4"
    mappings:
      - haier: 1
        value: high
      - haier: 2
        value: medium
      - haier: 3
        value: low
      - haier: 5
        value: auto
  - name: status
    id: "19"
  - name: target_temperature
    id: "0"

надо поправить файл api.py
после строки 311 вставить
device_model = device_model[:11]

было
            device_model = device_info.get("model", "AC")
            _LOGGER.debug(f"Device model {device_model}")`

стало
            device_model = device_info.get("model", "AC")
            device_model = device_model[:11]
            _LOGGER.debug(f"Device model {device_model}")`

судя по остальным моделям типо :CAS25CX1 и т.д спец символы появляются после 8 знаков
может резать название на 8 знаках

еще бы добавить управление шторкой, было бы вообще круто

**Comment by and7ey** [comment]
Добавлю конфиг, спасибо!
