### ISSUE TITLE
AS25S2SF2FA не поддерживается

### ISSUE THREAD

**Issue by AirAlarm** [and7ey/haier_evo#15]
Добрый день,

Проверено: Haier Flexis AS25S2SF2FA, не поддерживается.

[home-assistant_2024-07-16T16-28-09.538Z.log](https://github.com/user-attachments/files/16253771/home-assistant_2024-07-16T16-28-09.538Z.log)

Заработало после копирования профиля для AS20HPL2HRA в папке devices
![image](https://github.com/user-attachments/assets/e255fce5-3218-4e99-a041-3c2b7486c7e7)

**Comment by morrettogmail** [comment]
Аналогично с Haier Coral Expert -20C AS25PHP2HRA, жаль нет остальных функций из приложения типа самоочистки и регулировки наклона жалюзи.

**Comment by Ot4eVash** [comment]
> Добрый день,
> 
> Проверено: Haier Flexis AS25S2SF2FA, не поддерживается.
> 
> [home-assistant_2024-07-16T16-28-09.538Z.log](https://github.com/user-attachments/files/16253771/home-assistant_2024-07-16T16-28-09.538Z.log)
> 
> Заработало после копирования профиля для AS20HPL2HRA в папке devices ![image](https://private-user-images.githubusercontent.com/47337303/349208772-e255fce5-3218-4e99-a041-3c2b7486c7e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NTg5NDMsIm5iZiI6MTcyMTc1ODY0MywicGF0aCI6Ii80NzMzNzMwMy8zNDkyMDg3NzItZTI1NWZjZTUtMzIxOC00ZTk5LWEwNDEtM2MyYjc0ODZjN2U3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDE4MTcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1MjBiNGI3ZjQ0NTcxZGQ1ZjU4N2RkYzM3MDEyNTM0NmEyNzZiNDg3N2RlMzE3ZGQ1ZDg5YmM5MGNiNzYwMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2rFtKFImHKRWp0rKB4tG0SlRrPXo2nQzG77HxynfKIc)

А что именно скопировали? Можете подробнее? Такая-же проблема(((

**Comment by morrettogmail** [comment]
> > Добрый день,
> > Проверено: Haier Flexis AS25S2SF2FA, не поддерживается.
> > [home-assistant_2024-07-16T16-28-09.538Z.log](https://github.com/user-attachments/files/16253771/home-assistant_2024-07-16T16-28-09.538Z.log)
> > Заработало после копирования профиля для AS20HPL2HRA в папке devices ![image](https://private-user-images.githubusercontent.com/47337303/349208772-e255fce5-3218-4e99-a041-3c2b7486c7e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NTg5NDMsIm5iZiI6MTcyMTc1ODY0MywicGF0aCI6Ii80NzMzNzMwMy8zNDkyMDg3NzItZTI1NWZjZTUtMzIxOC00ZTk5LWEwNDEtM2MyYjc0ODZjN2U3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDE4MTcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1MjBiNGI3ZjQ0NTcxZGQ1ZjU4N2RkYzM3MDEyNTM0NmEyNzZiNDg3N2RlMzE3ZGQ1ZDg5YmM5MGNiNzYwMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2rFtKFImHKRWp0rKB4tG0SlRrPXo2nQzG77HxynfKIc)
> 
> А что именно скопировали? Можете подробнее? Такая-же проблема(((

В папке /custom_components/haier_evo/devices/

Копируем файл AS20HPL2HRA.yaml
Переименовываем его в свою модель кондиционера.

Потом я удалял устройство и добавлял заново.

**Comment by Ot4eVash** [comment]
> > > Добрый день,
> > > Проверено: Haier Flexis AS25S2SF2FA, не поддерживается.
> > > [home-assistant_2024-07-16T16-28-09.538Z.log](https://github.com/user-attachments/files/16253771/home-assistant_2024-07-16T16-28-09.538Z.log)
> > > Заработало после копирования профиля для AS20HPL2HRA в папке devices ![image](https://private-user-images.githubusercontent.com/47337303/349208772-e255fce5-3218-4e99-a041-3c2b7486c7e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NTg5NDMsIm5iZiI6MTcyMTc1ODY0MywicGF0aCI6Ii80NzMzNzMwMy8zNDkyMDg3NzItZTI1NWZjZTUtMzIxOC00ZTk5LWEwNDEtM2MyYjc0ODZjN2U3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDE4MTcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1MjBiNGI3ZjQ0NTcxZGQ1ZjU4N2RkYzM3MDEyNTM0NmEyNzZiNDg3N2RlMzE3ZGQ1ZDg5YmM5MGNiNzYwMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2rFtKFImHKRWp0rKB4tG0SlRrPXo2nQzG77HxynfKIc)
> > 
> > 
> > А что именно скопировали? Можете подробнее? Такая-же проблема(((
> 
> В папке /custom_components/haier_evo/devices/
> 
> Копируем файл AS20HPL2HRA.yaml Переименовываем его в свою модель кондиционера.
> 
> Потом я удалял устройство и добавлял заново.

Спасибо!

**Comment by and7ey** [comment]
Спасибо, добавлю конфиг!
