### ISSUE TITLE
HSU-12HPL203/R3(IN)

### ISSUE THREAD

**Issue by megamegalex** [and7ey/haier_evo#18]
HSU-12HPL203/R3(IN) не завелся, не реагирует 
пытался повторить этот конфиг https://github.com/and7ey/haier_evo/issues/14 не помогло
[home-assistant_haier_evo_2024-07-23T14-43-59.910Z.log](https://github.com/user-attachments/files/16359675/home-assistant_haier_evo_2024-07-23T14-43-59.910Z.log)

с логом возомжно перестарался, пардон

**Comment by alexxx113** [comment]
С логом точно перестарался, там ошибок куча.
Конфиг надеюсь в папке самой интеграции?
Правки в файлы внесли как я описал.
Если не править файлы, то можно просто сменить конфиг homeassistant/custom_components/haier_evo/devices/default.yaml
Прописав в нем как писал я

**Comment by megamegalex** [comment]
> Или поставить отсюда интеграцию Уже собрал человек готовую по моим правкам https://github.com/ada3000/haier_evo


завелось, спасибо

**Comment by zorgiy** [comment]
у меня не заводится модель - HSU-12HPL203/R3(IN), не находит и все ее

**Comment by and7ey** [comment]
добавлю в интеграцию, спасибо!
