### ISSUE TITLE
Подключается только одно устройство

### ISSUE THREAD

**Issue by RVetas** [and7ey/haier_evo#2]
Добрый день!
Спасибо за разработку этой интеграции.

Подключил свой аккаунт в интеграцию, но интеграция подключает только одно устройство из аккаунт. У меня два кондиционера одинаковой модели привязано к одному аккаунту. 

Собрал лог того, что происходит при нажатии кнопки "reload entries" в интеграции:
[clean_log.txt](https://github.com/user-attachments/files/15525858/clean_log.txt)
В нем можно увидеть, что с api приходят сообщения и о втором устройстве.

Буду ждать ответа

**Comment by and7ey** [comment]
Добрый день, список устройств определяется при первом добавлении интеграции (при логине). Т.е. нужно другие логи, чтобы посмотреть как это выглядит.

**Comment by 1vanchik** [comment]
Столкнулся с такой же проблемой, прикладываю логи. У меня в haier evo 3 кондиционера
[home-assistant_haier_evo_2024-06-03T21-56-38.975Z.log](https://github.com/user-attachments/files/15540251/home-assistant_haier_evo_2024-06-03T21-56-38.975Z.log)

**Comment by and7ey** [comment]
сделайте, пожалуйста, запрос (поменяв `<token>` на последний `accessToken` из лога)

```
curl --location 'https://evo.haieronline.ru/v2/ru/pages/sduiRawPaginated/smartHome?part=1&partitionWeight=6' \
--header 'Host: evo.haieronline.ru' \
--header 'Version: 4.7.0' \
--header 'Accept: */*' \
--header 'Time-zone: Europe/Moscow' \
--header 'Device-Id: DF311D14-2D9A-41E0-B07E-123456789012' \
--header 'Accept-Language: ru-RU;q=1.0, en-GB;q=0.9' \
--header 'Platform: ios' \
--header 'VersionCode: 9544' \
--header 'Device-model: Huawei' \
--header 'X-Auth-Token: <token>' \
--header 'User-Agent: evo-mobile' \
--header 'Connection: keep-alive' \
--header 'Content-Type: application/json'
```

**Comment by and7ey** [comment]
Попробуйте новую версию. 
С обновлением есть проблемы, после обновления проверяйте версию в manifest.json - должно быть 0.2.1. Возможно, потребуется полностью удалить файлы интеграции и добавить их снова.

**Comment by 1vanchik** [comment]
В релизе в директории custom_components/haier_evo старые файлы. Возможно из-за этого не обновляется. Сейчас при добавлении интеграции {"message":"Invalid handler specified"}

Какие файлы перезалить? Те, что в корне?

**Comment by and7ey** [comment]
> Какие файлы перезалить? Те, что в корне?
удалить все содержимое папки custom_components/haier_evo и заменить скачанными с гита файлами и папками

**Comment by 1vanchik** [comment]
в гите в папке [custom_components/haier_evo](https://github.com/and7ey/haier_evo/tree/main/custom_components/haier_evo) файлы 3-х недельной давности, проблема с обновлениями скорее всего из-за них

**Comment by 1vanchik** [comment]
После обновления файлом при попытке добавить интеграцию выдаёт ошибку: Не удалось загрузить мастер настройки: {"message":"Invalid handler specified"}

**Comment by and7ey** [comment]
> в гите в папке [custom_components/haier_evo](https://github.com/and7ey/haier_evo/tree/main/custom_components/haier_evo) файлы 3-х недельной давности, проблема с обновлениями скорее всего из-за них. И в архиве с релизом также
да, напутал структуру папок на гите, сейчас вроде все исправил, обновления должны работать


> После обновления файлом при попытке добавить интеграцию выдаёт ошибку: Не удалось загрузить мастер настройки: {"message":"Invalid handler specified"}
можно полный лог?
предыдущую интеграцию вы удаляли?

**Comment by 1vanchik** [comment]
Появились все кондиционеры, спасибо!

Однако в архиве с релизам в гитхаб файлы старые. Перенёс файлы в ручную

**Comment by and7ey** [comment]
> Появились все кондиционеры, спасибо!

проверьте еще, пожалуйста, что
1. работает управление всеми кондиционерами
2. правильно отображается изменение статус кондиционеров, при управлении из HA
3. правильно отображается изменение статуса при управлении с пульта

**Comment by TohaRG2** [comment]
Наконец то нашелся энтузиаст. :) У меня два кондиционера, один Haier Coral DC AS20HPL2HRA второй Haier Coral DC AS20HPL1HRA. Определяется только один Haier Coral DC AS20HPL2HRA, но к сожалению им не управляется. Лог - 
[home-assistant_haier_evo_2024-06-04T13-13-41.564Z.log](https://github.com/user-attachments/files/15551996/home-assistant_haier_evo_2024-06-04T13-13-41.564Z.log)

**Comment by and7ey** [comment]
> но к сожалению им не управляется

у вас очень старая версия, я ранее неправильно выкладывал файлы на гит, потому ничего не обновлялось, сегодня поправил - обновите и попробуйте снова

**Comment by TohaRG2** [comment]
Обновил.  Теперь определились оба кондиционера, но ни один не заработал к сожалению. Лог - 
[home-assistant_haier_evo_2024-06-04T13-45-02.448Z.log](https://github.com/user-attachments/files/15552433/home-assistant_haier_evo_2024-06-04T13-45-02.448Z.log)

**Comment by and7ey** [comment]
> Теперь определились оба кондиционера, но ни один не заработал к сожалению

у вас кондиционеры в приложении добавлены как умные и как не умные
я пока не придумал как их разделять, потому моя интеграция шлет команды неумным устройствам, что, конечно, не работает

удалите пока неумные устройства в evo

**Comment by TohaRG2** [comment]
Удалил "не умные" устройства в EVO. Интеграция перестала находить вообще какой-либо кондиционер. Удалил оба "умных" кондиционера в EVO. Добавил пока только один AS20HPL1HRA. Интеграция его находит, но панель управления им сначала не открывалась, но пока писал сообщение, заработало. Буду пробовать добавлять второй кондиционер. По результатам еще тогда напишу. Спасибо за интеграцию, появился шанс управлять кондеями через сеть из HA, а не через ИК пульт от EKF (Tuya) и сценарии забитые в TyuaSmart.

**Comment by TohaRG2** [comment]
Пробовал различные варианты, оставлял только какой-то один, подключал сначала  AS20HPL1HRA потом  AS20HPL2HRA, наоборот и т.д. В общем, как только подключаю в EVO  AS20HPL2HRA - перестает определять все что заведено в EVO.
Один AS20HPL1HRA - работает нормально.
Логи 
[home-assistant_haier_evo_один_AS20HPL2HRA.log](https://github.com/user-attachments/files/15573969/home-assistant_haier_evo_._AS20HPL2HRA.log)
[home-assistant_haier_evo_подключение_второго.log](https://github.com/user-attachments/files/15573970/home-assistant_haier_evo_._.log)

**Comment by and7ey** [comment]
Попробуйте новую версию. Сделал изменение, чтобы неумные устройства игнорировались.

**Comment by TohaRG2** [comment]
Огромное спасибо. Заработало. 
![image](https://github.com/and7ey/haier_evo/assets/47621988/b08c3eb1-2247-40c4-8a9a-cbda48504fcf)
