### ISSUE TITLE
AS25PS1HRA подтверждена работоспособность

### ISSUE THREAD

**Issue by tumb1er** [and7ey/haier_evo#8]
Конфиг `AS20HPL2HRA.yaml` подходит для указанной модели.

* Регулируется целевая температура
* Отображается текущая температура
* Переключаются режимы: Авто/охлаждение/нагрев/вентиляция/осушение/выключено
* Переключается скорость вентилятора: авто/низкая/средняя/высокая

Нет только обратной связи например при управлении через приложение EVO.

**Comment by and7ey** [comment]
Очень странно, что работает только в одну сторону.

Приложите логи, пожалуйста, - посмотрю в чем дело.

**Comment by tumb1er** [comment]
[haier.log](https://github.com/user-attachments/files/15837947/haier.log)

Переключал режимы с 15:15 до 15:16

TL;DR: 

> Got a message for a different device. Expected: 30:c9:22:06:58:34, got: 30:c9:22:05:2f:64

Если что, три одинаковых блока в одном аккаунте.

И обратной связи не то чтобы прям совсем нет - часть состояний пробивается.

**Comment by positiveviking** [comment]
Аналогичная проблема.
Предположу что причиной может быть открытие одинаковых websocket на каждое устройство и со стороны сервера сообщение посылается в один случайный.

Отсюда большинство сообщений отсекается [тут](https://github.com/and7ey/haier_evo/blob/fafa7a1d98caedb3b56529475852ad0b819ddefb/custom_components/haier_evo/api.py#L276) и иногда рандом заносит в нужный инстанс и "часть состояния пробивается"

**Comment by and7ey** [comment]
@tumb1er с версией 0.3.0 остались проблемы?

**Comment by tumb1er** [comment]
Вроде всё работает, спасибо
